<?php

/**
 * Implementation of hook_content_default_fields().
 */
function kt_audio_content_type_content_default_fields() {
  $fields = array();

  // Exported field: field_kt_audio_description
  $fields['kt_audio-field_kt_audio_description'] = array(
    'field_name' => 'field_kt_audio_description',
    'type_name' => 'kt_audio',
    'display_settings' => array(
      'weight' => '-18',
      'parent' => '',
      'label' => array(
        'format' => 'hidden',
      ),
      'teaser' => array(
        'format' => 'hidden',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '5' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '1',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => '3',
      'size' => 60,
      'default_value' => array(
        '0' => array(
          'value' => '',
          'format' => '1',
          '_error_element' => 'default_value_widget][field_kt_audio_description][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Description of the Audio',
      'weight' => '-1',
      'description' => 'Here you can add a long description with HTML for the Audio files',
      'type' => 'text_textarea',
      'module' => 'text',
    ),
  );

  // Exported field: field_kt_audios
  $fields['kt_audio-field_kt_audios'] = array(
    'field_name' => 'field_kt_audios',
    'type_name' => 'kt_audio',
    'display_settings' => array(
      'weight' => '-19',
      'parent' => '',
      'label' => array(
        'format' => 'hidden',
      ),
      'teaser' => array(
        'format' => 'hidden',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'swftools_no_file',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'filefield',
    'required' => '1',
    'multiple' => '1',
    'module' => 'filefield',
    'active' => '1',
    'list_field' => '1',
    'list_default' => 1,
    'description_field' => '1',
    'widget' => array(
      'file_extensions' => 'mp3 wav flacc ogg',
      'file_path' => 'audio/[site-date-yyyy]/[site-date-mm]/[site-date-dd]',
      'progress_indicator' => 'bar',
      'max_filesize_per_file' => '',
      'max_filesize_per_node' => '',
      'label' => 'Audio',
      'weight' => '-2',
      'description' => '',
      'type' => 'filefield_widget',
      'module' => 'filefield',
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Audio');
  t('Description of the Audio');

  return $fields;
}
